name: Cron

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  auto_predict:
    runs-on: ubuntu-22.04
      
    env:
      REGISTRY: "registry.digitalocean.com/dibimbing"
      IMAGE_NAME: "fastapi-recommender-system"
      PYTHONPATH: "app:$PYTHONPATH"
      
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Run the cron job
        run: docker run $REGISTRY/$IMAGE_NAME -f cronjob.dockerfile
